const ACTION_TYPE = {
  PRODUCT_DATA_LOADING: "PRODUCT_DATA_LOADING",
  PRODUCT_DATA_LOADING_SUCCESS: "PRODUCT_DATA_LOADING_SUCCESS",
  PRODUCT_DATA_LOADING_ERROR: "PRODUCT_DATA_LOADING_ERROR",
  ADD_PRODUCT: "ADD_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
};
export default ACTION_TYPE;
